### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by christensensm** [vertesy/ggExpress#18]
Trying to install ggExpress so that I can install Seurat.utils and running into the following error:

> devtools::install_github(repo = "vertesy/ggExpress@HEAD")
Downloading GitHub repo vertesy/ggExpress@HEAD
✓  checking for file ‘/tmp/Rtmpu9c30N/remotes19a625b7236/vertesy-ggExpress-ef9bab4/DESCRIPTION’ ...
─  preparing ‘ggExpress’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  building ‘ggExpress_0.2.2.tar.gz’
   
Installing package into ‘/sbgenomics/workspace/rpkgs’
(as ‘lib’ is unspecified)
* installing *source* package ‘ggExpress’ ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
[1] "Plot panels on 3-by-2 vertical A4 page."
Error in stopifnot(length(plot_list) < 7) : 
  object 'Fig.SX2.panels' not found
Error: unable to load R code in package ‘ggExpress’
Execution halted
ERROR: lazy loading failed for package ‘ggExpress’
* removing ‘/sbgenomics/workspace/rpkgs/ggExpress’
Error: Failed to install 'ggExpress' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmpu9c30N/file19a2a6ff6da/ggExpress_0.2.2.tar.gz’ had non-zero exit status

**Comment by vertesy** [comment]
Hi,

sorry it was a bug on my end. An accidental junk-line ended up in the code. Should work now. 

Let me know & good luck,
Abel

**Comment by christensensm** [comment]
Fixed now. Thanks!
